### Create auth token
# curl -X POST
#  https://restful-booker.herokuapp.com/auth
#  -H 'Content-Type: application/json'
#  -d '{
#    "username" : "admin",
#    "password" : "password123"
#}'
POST https://restful-booker.herokuapp.com/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

### Get all bookings
# curl -i https://restful-booker.herokuapp.com/booking
GET https://restful-booker.herokuapp.com/booking

### Get a particular booking
# curl -i https://restful-booker.herokuapp.com/booking/1
GET https://restful-booker.herokuapp.com/booking/485
Accept: application/json

### Create a booking
# curl -X POST
#  https://restful-booker.herokuapp.com/booking
#  -H 'Content-Type: application/json'
#  -d '{
#    "firstname" : "Jim",
#    "lastname" : "Brown",
#    "totalprice" : 111,
#    "depositpaid" : true,
#    "bookingdates" : {
#        "checkin" : "2018-01-01",
#        "checkout" : "2019-01-01"
#    },
#    "additionalneeds" : "Breakfast"
#}'
POST https://restful-booker.herokuapp.com/booking
Content-Type: application/json
Accept: application/json

{
  "firstname": "Jim",
  "lastname": "Brown",
  "totalprice": 111,
  "depositpaid": true,
  "bookingdates": {
    "checkin": "2018-01-01",
    "checkout": "2019-01-01"
  },
  "additionalneeds": "Breakfast"
}

### Update an existing booking
# curl -X PUT
#  https://restful-booker.herokuapp.com/booking/1
#  -H 'Content-Type: application/json'
#  -H 'Accept: application/json'
#  -H 'Cookie: token=abc123'
#  -d '{
#    "firstname" : "James",
#    "lastname" : "Brown",
#    "totalprice" : 111,
#    "depositpaid" : true,
#    "bookingdates" : {
#        "checkin" : "2018-01-01",
#        "checkout" : "2019-01-01"
#    },
#    "additionalneeds" : "Breakfast"
#}'
PUT https://restful-booker.herokuapp.com/booking/8261
Accept: application/json
Cookie: token=e70893a48b15faf
Content-Type: application/json

{
  "firstname": "Pramod",
  "lastname": "Yadav",
  "totalprice": 111,
  "depositpaid": true,
  "bookingdates": {
    "checkin": "2018-01-01",
    "checkout": "2019-01-01"
  },
  "additionalneeds": "Breakfast"
}

### Partial update a booking
# curl -X PATCH
#  https://restful-booker.herokuapp.com/booking/1
#  -H 'Content-Type: application/json'
#  -H 'Accept: application/json'
#  -H 'Cookie: token=abc123'
#  -d '{
#    "firstname" : "James",
#    "lastname" : "Brown"
#}'
PATCH https://restful-booker.herokuapp.com/booking/8261
Accept: application/json
Cookie: token=e70893a48b15faf
Content-Type: application/json

{
  "firstname": "Vinod",
  "lastname": "kumar"
}

### Delete booking
# curl -X DELETE
#  https://restful-booker.herokuapp.com/booking/1
#  -H 'Content-Type: application/json'
#  -H 'Cookie: token=abc123'
DELETE https://restful-booker.herokuapp.com/booking/686
Cookie: token=99999c8c94b4d33
Content-Type: application/json

### health check endpoint
# curl -i https://restful-booker.herokuapp.com/ping
GET https://restful-booker.herokuapp.com/ping

###













